import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DigijjdddNews",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <ClerkProvider>
    <html lang="en">
      <body>
        <SignedOut>
          <SignInButton />
          login
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
        hello
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
